spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm_crud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: qwerty1216
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      max-wait-millis: 10000
      min-idle: 5
      driver-class-name: com.mysql.cj.jdbc.Driver

#server:
#  port: 8081

mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: me.chon.boot.bean